#!/usr/bin/env python3
"""Assemble the publishable Excel add-in into docs/addin/.

GitHub Pages serves docs/ from main, so everything written here goes
live at https://ibushimaru.github.io/felix-tm/addin/ on the next push.

The dev tree (plugins/excel-addin/) references felix-engine.js / db.js
via dev-server aliases into plugins/chrome-extension/ — the live source
stays the single source of truth. This script materialises real copies
for static hosting and rewrites the manifest for the hosted origin.

The production manifest gets its own GUID (PROD_ID below) so a tester
can keep the localhost dev manifest sideloaded next to the published
one without Office treating them as the same add-in.

Output:
  docs/addin/manifest.xml      — production manifest (hosted URLs)
  docs/addin/taskpane.*        — pane UI
  docs/addin/felix-engine.js   — copied from plugins/chrome-extension/
  docs/addin/db.js             — copied from plugins/chrome-extension/
  docs/addin/icons/            — copied from plugins/chrome-extension/icons/

Usage: python3 scripts/build_addin.py
"""

from __future__ import annotations

import re
import shutil
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
ADDIN = REPO / "plugins" / "excel-addin"
EXT = REPO / "plugins" / "chrome-extension"
OUT = REPO / "docs" / "addin"

BASE_URL = "https://ibushimaru.github.io/felix-tm/addin"

# Dev manifest GUID → production GUID. Fixed values: regenerating the
# prod GUID on every build would make Office register each build as a
# brand-new add-in.
DEV_ID = "9ef5b4ad-75d5-4ad8-99a1-4f5dc3678e81"
PROD_ID = "4ab5202e-760b-402b-8999-84495bcca008"


def build_manifest() -> str:
    xml = (ADDIN / "manifest.xml").read_text(encoding="utf-8")
    xml = xml.replace(DEV_ID, PROD_ID)
    xml = xml.replace("https://localhost:3000", BASE_URL)
    # The dev-manifest header comment describes localhost sideloading;
    # replace it with a pointer back to the build script.
    xml = re.sub(
        r"<!--.*?-->",
        "<!-- Generated by scripts/build_addin.py — do not edit by hand. -->",
        xml,
        count=1,
        flags=re.S,
    )
    return xml


def main() -> int:
    if OUT.exists():
        shutil.rmtree(OUT)
    OUT.mkdir(parents=True)

    for name in ("taskpane.html", "taskpane.css", "taskpane.js", "shortcuts.json",
                 "install-windows.bat", "uninstall-windows.bat", "install-windows.ps1",
                 "install-mac.sh", "uninstall-mac.sh"):
        shutil.copy2(ADDIN / name, OUT / name)
    for name in ("felix-engine.js", "db.js"):
        shutil.copy2(EXT / name, OUT / name)
    shutil.copytree(EXT / "icons", OUT / "icons")

    (OUT / "manifest.xml").write_text(build_manifest(), encoding="utf-8")

    files = sorted(p.relative_to(OUT).as_posix() for p in OUT.rglob("*") if p.is_file())
    print(f"Built {OUT.relative_to(REPO)} ({len(files)} files):")
    for f in files:
        print(f"  {f}")
    print(f"\nServes at: {BASE_URL}/taskpane.html")
    return 0


if __name__ == "__main__":
    sys.exit(main())
